Squashed 'images/llama-cpp-python/vendor/llama.cpp/' changes from 1cfb5372..cb49e0f8
cb49e0f8 Attempt to fix android build (#5752)
0becb22a IQ4_XS: a 4.25 bpw quantization (#5747)
c24a2a6e cuda : replace remaining shfl_xor with calls to warp_reduce functions (#5744)
1f30b7a9 ggml-quants : fix avx2 iq1_s vec_dot when compiled with gcc (#5742)
9d533a77 llama : fix defrag bugs + add parameter (#5735)
cbbd1efa Makefile: use variables for cublas (#5689)
b11a93df fix server hangs on empty prompt (#5733)
a33e6a0d Adding IQ2_S and IQ2_M to complete coverage of the 2-3 bit quantization range (#5721)
47bb7b48 CUDA: fix DEBUG_CUDA_MALLOC (#5729)
c4d7f817 readme : update ui list (#5731)
e849078c [SYCL] Add support for soft_max ALiBi (#5639)
67fd3313 unicode : reuse iterator (#5726)
4804215c server: CI fix trailing space (#5728)
8a533f0d server: CI tests reduce build matrix (#5725)
269de86b llama : fix Gemma rope type (#5691)
c3937339 flake.lock: Update
e3965cf3 server: tests - slow inference causes timeout on the CI (#5715)
8b350356 server: docs - refresh and tease a little bit more the http server (#5718)
bf08e006 llama : refactor k-shift implementation + KV defragmentation (#5691)
f7625019 server : fix crash when system prompt is bigger than batch size (#5714)
abbabc5e ggml-quants : provide ggml_vqtbl1q_u8 for 64bit compatibility (#5711)
f1a98c52 make : fix nvcc version is empty (#5713)
7d548a18 readme : add Msty to UI list (#5618)
930b1780 server: logs - unified format and --log-format option (#5700)
d52d7819 server: concurrency fix + monitoring - add /metrics prometheus compatible endpoint (#5708)
12894088 cmake : fix compilation for Android armeabi-v7a (#5702)
ab336a9d code : normalize enum names (#5697)
69917dfa py : fix StableLM conversion after config.json changes (#5703)
9e359a4f server: continue to update other slots on embedding concurrent request (#5699)
4c4cb307 IQ3_S: a much better alternative to Q3_K (#5676)
525213d2 server: init functional tests (#5566)
fd43d66f server : add KV cache quantization options (#5684)
54fbcd2c convert : fix missing ftype for gemma (#5690)
15499eb9 mpt : do not duplicate token_embd.weight on disk (#5670)
96633eec gemma : use more bits for the token_embd.weight tensor (#5650)
847eedbd py : add Gemma conversion from HF models (#5647)
7e4f339c ggml : always define ggml_fp16_t as uint16_t (#5666)
334f76fa sync : ggml
efd56b1c ggml : 32-bit arm compat (whisper/1891)
201294ae nix: init singularity and docker images (#5056)
5a9e2f60 py : minor fixes (#5668)
373ee3fb Add Gemma chat template (#5665)
4cb4d8b2 workflows: nix: hardcode cachix ids, build unconditionally (#5663)
3a03541c minor : fix trailing whitespace (#5638)
56d03d92 readme : update hot topics
a46f5074 server : fallback to chatml, add AlphaMonarch chat template (#5628)
c5688c62 server : clarify some params in the docs (#5640)
4ef245a9 mpt : add optional bias tensors (#5638)
973053d8 llama : fix loading models with shared tok_embd and output (#5651)
7c8bcc11 Add docs for llama_chat_apply_template (#5645)
7fe4678b llama : fix session save/load with quantized KV (#5649)
ba2135cc gemma : allow offloading the output tensor (#5646)
89febfed examples : do not assume BOS when shifting context (#5622)
5022cf24 sync : ggml
1ecea255 server: health: fix race condition on slots data using tasks queue (#5634)
a00a35ce readme : add LocalAI to the availables UI (#5629)
eccd7a26 sync : ggml (#5633)
c14f72db readme : update hot topics
cc6cac08 llava : add --skip-unknown to 1.6 convert.py (#5632)
580111d4 llama : add `gemma` model (#5631)
88c46cbd [SYCL] conext add name (#5624)
a14679cc IQ4_NL: 4-bit non-linear quants with blocks of 32 (#5590)
6560bed3 server : support llava 1.6 (#5553)
06bf2cf8 make : fix debug build with CUDA (#5616)
4ed8e4fb llava : add explicit instructions for llava-1.6 (#5611)
9c405c9f Server: use llama_chat_apply_template (#5593)
5207b3fb readme : update UI list (#5605)
8dbbd757 metal : add build system support for embedded metal library (#5604)
c0a8c6db server : health endpoint configurable failure on no slot (#5594)
b9111bd2 Update ggml_sycl_op_mul_mat_vec_q (#5502)
633782b8 nix: now that we can do so, allow MacOS to build Vulkan binaries
22f83f0c Enable Vulkan MacOS CI
bb9dcd56 Refactor validation and enumeration platform checks into functions to clean up ggml_vk_instance_init()
f50db6ae Add check for VK_KHR_portability_enumeration for MoltenVK support
d8c05451 Add preprocessor checks for Apple devices.
42f664a3 Resolve ErrorIncompatibleDriver with Vulkan on MacOS.
5dde5408 Allow for Vulkan build with Accelerate.
40c3a6c1 cuda : ignore peer access already enabled errors (#5597)
f24ed14e make : pass CPPFLAGS directly to nvcc, not via -Xcompiler (#5598)
9d679f0f examples : support minItems/maxItems in JSON grammar converter (#5039)
1387cf60 llava : remove extra cont (#5587)
6fd41379 llava : replace ggml_cpy with ggml_cont
337c9cbd sync : ggml
a3145bdc ggml-alloc : apply ggml/731
890559ab metal : option to embed MSL source into compiled binary (whisper/1842)
d0e3ce51 ci : enable -Werror for CUDA builds (#5579)
68a6b98b make : fix CUDA build (#5580)
70d45af0 readme : fix typo in README-sycl.md (#5353)
13e2c771 cmake : remove obsolete sycl compile flags (#5581)
f53119ce minor : fix trailing whitespace (#5538)
70847553 llava : avoid changing the original BakLLaVA model (#5577)
4480542b baby-llama : allocate graphs in ggml_context (#5573)
11b12de3 llama : add llama_chat_apply_template() (#5538)
3a9cb4ca cuda, metal : fix nans in soft_max (#5574)
769a716e readme : update (#5572)
f0d1fafc ggml : android and old glibc NUMA incompatibility bugfixes (#5557)
a0c2dad9 build : pass all warning flags to nvcc via -Xcompiler (#5570)
14278f55 ggml : restore vec dot stride arg names (#5453)
b1de9682 ci : fix wikitext url + compile warnings (#5569)
7ad554f9 metal : fix unused warnings (#0)
5ee99c32 common, server : surface min_keep as its own parameter (#5567)
c145f8a1 server : slots monitoring endpoint (#5550)
689a091b sampling : do not set min_keep to n_probs (#5564)
f3f28c53 cmake : fix GGML_USE_SYCL typo (#5555)
e75c6279 server : enhanced health endpoint (#5548)
36376abe server : --n-predict option document and cap to max value (#5549)
66c1968f server : graceful server shutdown (#5244)
1dcc3fde common : fix ub (#5530)
5d3de51f ggml, common, examples, tests : fixed type arguments in printf (#5528)
fc0c8d28 llava : update surgery script to not remove tensors (#5536)
bd2d4e39 1.5 bit quantization (#5453)
c8e0d7ef flake.lock: Update
8f1be0d4 ggml : add ALiBi support for ggml_soft_max_ext (#5488)
6e4e973b ci : add an option to fail on compile warning (#3952)
d250c9d6 gitignore : update for CLion IDE (#5544)
5bf2b94d cmake : fix VULKAN and ROCm builds (#5525)
d2819d55 scripts : add helpers script for bench comparing commits (#5521)
4cb07276 llava : removed excess free(NULL) operation (#5531)
65085c71 llama : minor fixed return int value (#5529)
6dcc02d2 server : add "samplers" param to control the samplers order (#5494)
5f5808ca server : fix system prompt cli (#5516)
f486f6e1 ggml : add numa options (#5377)
60ed04cf llava : fix clip-model-is-vision flag in README.md (#5509)
594845aa ci : fix BERT model download and convert
4524290e Use correct type of pooling for embedding models (#5500)
c06e45d7 clip : fix wrong loop condition
9060a1e9 cuda : print message when initialization fails (#5512)
9350a1cf scripts : add hf.sh helper script (#5501)
73122473 fix(gguf-py): special tokens are no longer skipped when add_<token>_token is set to false (#5487)
0d417712 llava : fix memory management bug (#5491)
7930a8a6 llaba : hotfix for llava-1.6 image number (#5495)
704359e2 vulkan: Find optimal memory type but with fallback (#5381)
594fca3f readme : fix typo (#5490)
ccbb277f llava : update README.md (#5489)
8084d554 cmake : ARM intrinsics detection for MSVC (#5401)
aa234129 llava : support v1.6 (#5267)
f5ca0548 Early return for zero size calls to get_tensor. (#5482)
6c00a066 gguf : add python reader example (#5216)
ea9c8e11 llama : add support for Nomic Embed (#5468)
c4e6dd59 llama : allow raw byte in SPM vocabs; don't crash on nl 404 (#5478)
037259be llama : make load error reporting more granular (#5477)
26397890 finetune : rename feed-forward tensors (w1/w2/w3) (#4839)
cf45252a tests : multi-thread the tokenizer tests (#5474)
03bf161e llama : support batched embeddings (#5466)
ad014bba make: add error message for bad CUDA version (#5444)
49cc1f7d bert : add tests + fix quantization (#5475)
99b8b43d tests : disable moe test (#5473)
895407f3 ggml-quants : fix compiler warnings (shadow variable) (#5472)
099afc62 llama : fix quantization when tensors are missing (#5423)
df334a11 swift : package no longer use ggml dependency (#5465)
dbd8828e py : fix persimmon `n_rot` conversion (#5460)
43fe07c1 ggml-sycl: Replace 3d ops with macro  (#5458)
4a46d2b7 llava : remove prog parameter from ArgumentParser (#5457)
3b169441 sync : ggml (#5452)
3bdc4cd0 CUDA: mul_mat_vec_q tiling, refactor mul mat logic (#5434)
2891c8aa Add support for BERT embedding models (#5423)
97a33650 flake.lock: Update
c88c74f9 vulkan: only use M-sized matmul on Apple GPUs (#5412)
a803333a common : use enums for sampler types (#5418)
68478014 server : allow to specify tokens as strings in logit_bias (#5003)
85910c5b main : ctrl+C print timing in non-interactive mode (#3873)
139b62a8 common : fix compile warning
0f2411f1 ggml : fix compile warnings (unused vars) (#4966)
a07d0fee ggml : add mmla kernels for quantized GEMM (#4966)
e4640d8f lookup: add print for drafting performance (#5450)
907e08c1 server : add llama2 chat template (#5425)
f026f812 metal : use autoreleasepool to avoid memory leaks (#5437)
cd9aea63 scripts : update sync scripts with new backends
43b65f5e sync : ggml
4633d93a ggml : add abort_callback for cpu backend (ggml/725)
4b7b38be vulkan: Set limit for task concurrency (#5427)
e00d2a62 llava : add requirements.txt and update README.md (#5428)
7c777fcd server : fix prompt caching for repeated prompts (#5420)
e5ca3937 llama : do not cap thread count when MoE on CPU (#5419)
e4124c24 readme : add JavaScript/Wasm repo (#5415)
b2f87cb6 ggml : fix `error C2078: too many initializers` for MSVC ARM64 (#5404)
44fbe343 Fix Vulkan crash on APUs with very little device memory (#5424)
8e6a9d2d CUDA: more warps for mmvq on NVIDIA (#5394)
41f308f5 llama : do not print "offloading layers" message in CPU-only builds (#5416)
6e99f2a0 Fix f16_sycl cpy call from Arc (#5411)
ff4ff05c llava : add missing .py, and fix paths in README.md (#5414)
b7b74cef fix trailing whitespace (#5407)
4aa43fab llama : fix MiniCPM (#5392)
a6e514a8 llava: fix typo/formatting in README.md (#5405)
26d4efd1 sampling: fix top_k <= 0 (#5388)
8504d2d0 tests : .gitignore obj files
c4fbb671 CMAKE_OSX_ARCHITECTURES for MacOS cross compilation (#5393)
8c933b70 fix typo in readme (#5399)
b906596b Add Ava in the list of llama.cpp UIs (#4362)
aa7ab99b CUDA: fixed mmvq kernel for bs 2,3,4 and -sm row (#5386)
10afa6f1 [SYCL] update install make by w64devkit (#5297)
0ef46da6 llava-cli : always tokenize special tokens (#5382)
ee1628bd Basic Vulkan Multi-GPU implementation (#5321)
ed0bf322 readme : modernize (#5379)
9a697d84 readme : update ui list (#5354)
316c7faf llama : add MiniCPM support (#5346)
f3e2b4fa server : update `/props` with "total_slots" value (#5373)
f68664ac convert : fix TypeError on GPT-2 vocab.json (#5288)
213d1439 server : remove model.json endpoint (#5371)
17c97fb0 CUDA: mul_mat_vec_q max. batch size 8 -> 4 (#5370)
b08f22c8 Update README.md (#5366)
f57fadc0 Slight quantization improvement for Q4_K and Q5_K (#5361)
2e9c0bd6 readme : add phi, orion 14b, internlm2, and yi-VL to readme (#5362)
2c516611 CUDA: mul_mat_vec_q for batch sizes > 1 (#5351)
8a79c591 server : include total "num_slots" in props endpoint (#5349)
31e79032 server : add `dynatemp_range` and `dynatemp_exponent` (#5352)
4ffc7a17 server : various fixes for the prompt field in /completion (#5300)
906cff55 py : handle byte tokens in `get_token_type` (#5341)
098f6d73 make: Use ccache for faster compilation (#5318)
78b00dda README: updated introduction (#5343)
c6b39553 ggml : make use of ggml-quants.h possible in C++ code (#5338)
abb61944 ggml : avoid duplicating function calls using MIN/MAX macros (#5325)
89503dcb iq3_xxs: quards for the no-imatrix situation (#5334)
7e1ae372 py : fix internlm2-hf convert to gguf (#5305)
6fdfa2ec iq2_xxs: tune quantization (#5320)
a2d60c91 server : allow to get default generation settings for completion (#5307)
e6f81775 common : add dynamic temperature parameters to main example cli (#5295)
30679d43 scripts : fix typos, cleanup (#5303)
4be04c89 scripts : add non-interactive server-llm.sh (#5303)
5d55b0cd readme : add CodeShell models to the supported models list (#5330)
4833ac20 [SYCL] Fix cpy with dims of 3 (#5289)
9392ebd4 flake.lock: Update
5ed26e1f Adding some imatrix tools (#5302)
277fad30 cmake : use set() for LLAMA_WIN_VER (#5298)
3c0d25c4 make: add nvcc info print (#5310)
3cc5ed35 make: fix nvcc optimization flags for host code (#5309)
60ecf099 add Vulkan support to Nix flake
e920ed39 Vulkan Intel Fixes, Optimizations and Debugging Flags (#5301)
52bb63c7 refactor : switch to emplace_back to avoid extra object (#5291)
1ec3332a YaRN : store rope scaling type as int32_t in memory (#5285)
6a66c507 readme : add tenere in the ui tools list (#5284)
a305dba8 Fix im2col with 32fp (#5286)
19122117 perplexity : fix KL divergence calculations on Windows (#5273)
e437b37f scripts : parse wtype in server-llm.sh (#5167)
2d40085c py : add check for '.attn.masked_bias' layers to GPT2model (#5281)
b05102fe Tidy ggml-sycl (#5261)
6b91b1e0 docker : add build for SYCL, Vulkan + update readme (#5228)
e805f0fa [SYCL] get MAX_MEM_ALLOC from device property (#5270)
af3ba5d9 [SYCL] update guide of SYCL backend (#5254)
e1e72109 llama : fix memory leak in llama_batch_free (#5252)
128dcbd3 add --no-mmap in llama-bench (#5257)
4d0924a8 Vulkan Phi Fix for AMD Proprietary Drivers (#5260)
8ca511ca cuda : fix LLAMA_CUDA_F16 (#5262)
d71ac909 make : generate .a library for static linking (#5205)
ce320601 llama : support InternLM2 (#5184)

git-subtree-dir: images/llama-cpp-python/vendor/llama.cpp
git-subtree-split: cb49e0f8c906e5da49e9f6d64a57742a9a241c6a